/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResumeLabRouteImport } from './routes/resume-lab'
import { Route as RecruiterInboxRouteImport } from './routes/recruiter-inbox'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCronScrapeJobsRouteImport } from './routes/api/public/cron/scrape-jobs'
import { Route as ApiPublicCronGmailSyncRouteImport } from './routes/api/public/cron/gmail-sync'
import { Route as ApiPublicCronDailyBriefingRouteImport } from './routes/api/public/cron/daily-briefing'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeLabRoute = ResumeLabRouteImport.update({
  id: '/resume-lab',
  path: '/resume-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterInboxRoute = RecruiterInboxRouteImport.update({
  id: '/recruiter-inbox',
  path: '/recruiter-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronScrapeJobsRoute = ApiPublicCronScrapeJobsRouteImport.update({
  id: '/api/public/cron/scrape-jobs',
  path: '/api/public/cron/scrape-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronGmailSyncRoute = ApiPublicCronGmailSyncRouteImport.update({
  id: '/api/public/cron/gmail-sync',
  path: '/api/public/cron/gmail-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDailyBriefingRoute =
  ApiPublicCronDailyBriefingRouteImport.update({
    id: '/api/public/cron/daily-briefing',
    path: '/api/public/cron/daily-briefing',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/blog': typeof BlogRoute
  '/briefing': typeof BriefingRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/integrations': typeof IntegrationsRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/recruiter-inbox': typeof RecruiterInboxRoute
  '/resume-lab': typeof ResumeLabRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/public/cron/daily-briefing': typeof ApiPublicCronDailyBriefingRoute
  '/api/public/cron/gmail-sync': typeof ApiPublicCronGmailSyncRoute
  '/api/public/cron/scrape-jobs': typeof ApiPublicCronScrapeJobsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/blog': typeof BlogRoute
  '/briefing': typeof BriefingRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/integrations': typeof IntegrationsRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/recruiter-inbox': typeof RecruiterInboxRoute
  '/resume-lab': typeof ResumeLabRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/public/cron/daily-briefing': typeof ApiPublicCronDailyBriefingRoute
  '/api/public/cron/gmail-sync': typeof ApiPublicCronGmailSyncRoute
  '/api/public/cron/scrape-jobs': typeof ApiPublicCronScrapeJobsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/blog': typeof BlogRoute
  '/briefing': typeof BriefingRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/integrations': typeof IntegrationsRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/recruiter-inbox': typeof RecruiterInboxRoute
  '/resume-lab': typeof ResumeLabRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/public/cron/daily-briefing': typeof ApiPublicCronDailyBriefingRoute
  '/api/public/cron/gmail-sync': typeof ApiPublicCronGmailSyncRoute
  '/api/public/cron/scrape-jobs': typeof ApiPublicCronScrapeJobsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/applications'
    | '/blog'
    | '/briefing'
    | '/calendar'
    | '/dashboard'
    | '/integrations'
    | '/jobs'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/recruiter-inbox'
    | '/resume-lab'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/api/public/cron/daily-briefing'
    | '/api/public/cron/gmail-sync'
    | '/api/public/cron/scrape-jobs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/applications'
    | '/blog'
    | '/briefing'
    | '/calendar'
    | '/dashboard'
    | '/integrations'
    | '/jobs'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/recruiter-inbox'
    | '/resume-lab'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/api/public/cron/daily-briefing'
    | '/api/public/cron/gmail-sync'
    | '/api/public/cron/scrape-jobs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/applications'
    | '/blog'
    | '/briefing'
    | '/calendar'
    | '/dashboard'
    | '/integrations'
    | '/jobs'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/recruiter-inbox'
    | '/resume-lab'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/api/public/cron/daily-briefing'
    | '/api/public/cron/gmail-sync'
    | '/api/public/cron/scrape-jobs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplicationsRoute: typeof ApplicationsRoute
  BlogRoute: typeof BlogRoute
  BriefingRoute: typeof BriefingRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  IntegrationsRoute: typeof IntegrationsRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  RecruiterInboxRoute: typeof RecruiterInboxRoute
  ResumeLabRoute: typeof ResumeLabRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiPublicCronDailyBriefingRoute: typeof ApiPublicCronDailyBriefingRoute
  ApiPublicCronGmailSyncRoute: typeof ApiPublicCronGmailSyncRoute
  ApiPublicCronScrapeJobsRoute: typeof ApiPublicCronScrapeJobsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-lab': {
      id: '/resume-lab'
      path: '/resume-lab'
      fullPath: '/resume-lab'
      preLoaderRoute: typeof ResumeLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter-inbox': {
      id: '/recruiter-inbox'
      path: '/recruiter-inbox'
      fullPath: '/recruiter-inbox'
      preLoaderRoute: typeof RecruiterInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scrape-jobs': {
      id: '/api/public/cron/scrape-jobs'
      path: '/api/public/cron/scrape-jobs'
      fullPath: '/api/public/cron/scrape-jobs'
      preLoaderRoute: typeof ApiPublicCronScrapeJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/gmail-sync': {
      id: '/api/public/cron/gmail-sync'
      path: '/api/public/cron/gmail-sync'
      fullPath: '/api/public/cron/gmail-sync'
      preLoaderRoute: typeof ApiPublicCronGmailSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily-briefing': {
      id: '/api/public/cron/daily-briefing'
      path: '/api/public/cron/daily-briefing'
      fullPath: '/api/public/cron/daily-briefing'
      preLoaderRoute: typeof ApiPublicCronDailyBriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplicationsRoute: ApplicationsRoute,
  BlogRoute: BlogRoute,
  BriefingRoute: BriefingRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  IntegrationsRoute: IntegrationsRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  RecruiterInboxRoute: RecruiterInboxRoute,
  ResumeLabRoute: ResumeLabRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiPublicCronDailyBriefingRoute: ApiPublicCronDailyBriefingRoute,
  ApiPublicCronGmailSyncRoute: ApiPublicCronGmailSyncRoute,
  ApiPublicCronScrapeJobsRoute: ApiPublicCronScrapeJobsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
